### DISCUSSION TITLE
Are you using this? If yes, why, if no, why not?

### DISCUSSION THREAD

**Discussion by SmilyOrg** [SmilyOrg/photofield#83] [General]
Hey all! For some reason, I'm still working on this 🤷‍♂️

I realized it's gotten to the point where it probably needs some better documentation so that people know what the hell this even is and how to use it, [v0.13.0](https://github.com/SmilyOrg/photofield/releases/tag/v0.13.0) is the first step towards that. I hope to improve that a bit and also fix some of the bugs that are annoying me currently and then promote it some more :)

💡 That lead me to thinking that I don't know whether and how anyone is actually using this. I don't have any tracking or analytics beyond container image download counts, so I thought to reach out to you folks through these discussions directly.

So if you're reading this, I'd appreciate it if you left a signal on what is and is not important to you when it comes to this project.

**What is stopping you from using it? What do you like the most? What bugs you the most? Where would you like it to go next?**

Feel free to just drop any comment here, [leave a reaction on an issue](https://github.com/SmilyOrg/photofield/issues) (I added a few new ones!) or send me an email (link in [profile](https://github.com/SmilyOrg)).

Thanks! 🙏

**Comment by MironPascalCaseFan** [comment]
Man, this is just an amazing piece of tech. I gathered all my photos and videos from the drives I had, and cataloged them by date using Elodie (an exiftool wrapper). 
![IMG_20260106_003450529](https://github.com/user-attachments/assets/ac5b8730-5d6e-4c59-ba58-4a64cc34e697)


The next step? View this treasure somehow. Immich and other stuff missed the point for me. I was just looking for a robyst image viewer that reads files exactly how they are in the folder. And then I found this. It outperformed all my expectations. It is blazingly fast and web ui works on mobile too. Just amazing. Thanks for your work.
<img width="542" height="1206" alt="Screenshot_20260106-003308" src="https://github.com/user-attachments/assets/75c7f5bf-c321-44eb-bc80-c6149a60c8b4" />

It is really fast. UI is flawless, no lags, super responsive, really convenient even on mobile. Very minimalistic. Just read only viewing and nothing more. I am planning to do synchronization with my devices my own way. I don’t need Imich. I want to keep my photos and videos in the structure I decide and not be dependent on the app. The only thing I wish it had is some kind of view filter so I can choose to watch only video files, etc.
...
Also, I have some files in MOV containers (iOS writes videos in them) and unfortunately photofield doesn’t pick them up yet.
Same goes for .HEIC (iOS photo format).

**Reply by SmilyOrg** [reply]
Hi! Thanks for describing your use case! It's very helpful feedback :)

Filtering to video only would be a nice additional search qualifier to add for sure.

On the MOV, maybe you can try customizing the extensions in the configuration.yaml to include it and see if it works for you. Your browser would need to support MOV playback natively for now though.

On HEIC, this seemed difficult to support before, but it seems like ffmpeg added support for it in the meantime, so maybe it's as easy as updating to a newer version and enabling it in extensions now? 🤔

**Reply by MironPascalCaseFan** [reply]
So, my config now is:

```yaml
collections:
  - name: Life
    dirs:
      - /media/miron/Expansion/MironLifePhotosVideos/

media:
  ffmpeg_path: /home/miron/realhome/photofield/ffmpeg
  extensions: [
    ".jpg", ".jpeg", ".png", ".avif", ".bmp", ".pam", ".ppm", ".jxl", ".exr", ".cr2", ".dng",
    ".mp4", ".mov", ".heic"
  ]
  images:
    extensions: [".jpg", ".jpeg", ".png", ".avif", ".bmp", ".pam", ".ppm", ".jxl", ".exr", ".cr2", ".dng", ".heic"]
  videos:
    extensions: [".mp4", ".mov"]

```

I reindexed the collection and it finally found these 2,000 MOV and HEIC files. But they are not showing up in the web UI. They are in the database, but they aren’t displayed

Idk if it matters but this is my ffmpeg version:
<img width="3200" height="768" alt="image" src="https://github.com/user-attachments/assets/29297c64-505a-479e-894c-9066f547dbc6" />


And this is what I get if I try to reindex again
<img width="3200" height="1444" alt="image" src="https://github.com/user-attachments/assets/4815861d-3734-4401-8173-46d0fdc937d3" />


photofield version:
```bash
photofield v0.21.0, commit 9926c72efc1e15c95f8ccb07ff8cfed1c212295e, built on 2026-01-01T21:49:41Z by runner
```
