### ISSUE TITLE
Can't start docker setup even with minmal configuration

### ISSUE THREAD

**Issue by Dukobpa3** [SmilyOrg/photofield#124]
**Describe the bug**
Trying to setup server but something going wrong

```
photofield 0.16.0
config path data/configuration.yaml
geo using file:data/geo/geoBoundariesCGAZ_ADM2_s5_twkb_p3.gpkg?vfs=vfs1&mode=ro
cache database version 15, migrating if needed
ffmpeg found at /usr/bin/ffmpeg
thumbs database version 1, migrating if needed
extensions .jpg, .jpeg, .png, .avif, .bmp, .pam, .ppm, .jxl, .exr, .cr2, .dng, .mp4
3 collections
  timeline - 0 files indexed N/A ago
  inbox - 0 files indexed N/A ago
  albums - 0 files indexed N/A ago
app running (api under /api)
  local    http://127.0.0.1:8080
  network  http://172.21.0.2:8080
  local    http://[::1]:8080
scene loading timeline
get prefix ids           0 ms
list infos get dirs      0 ms
list infos dirs 0
list infos               0 ms
list infos sqlite        0 ms
panic: sqlite: prepare "\n\t\t\tSELECT * FROM (\n\t\t\n\t\t\t)\n\t\t\tORDER BY created_at_unix ASC\n\t\t\t;": SQL logic error: near ")": syntax error
goroutine 289 [running]:
zombiezen.com/go/sqlite.(*Conn).Prep(0xc0003a6410, {0xc0003a3380, 0x40})
	/home/runner/go/pkg/mod/zombiezen.com/go/sqlite@v0.13.1/sqlite.go:419 +0x129
photofield/internal/image.(*Database).listWithPrefixIds.func1()
	/home/runner/work/photofield/photofield/internal/image/database.go:1932 +0x7a5
created by photofield/internal/image.(*Database).listWithPrefixIds in goroutine 218
	/home/runner/work/photofield/photofield/internal/image/database.go:1783 +0x25a
```

**To Reproduce**
I'm not sure because it is first setup

There is remote folders connected by NFS
Nothing special except that

Config:
```yml
# Defines collections / albums that are scanned and shown in the UI
collections:
  # By default show all subdirs of the current working directory
  - expand_subdirs: true
    expand_sort: desc
    dirs: 
      - "/photo"
```

Compose.yml
```yml
services:
  photofield:
    image: ghcr.io/smilyorg/photofield:latest
    container_name: photofield
    ports:
      - 8080:8080
    user: 1000:1000
    volumes:
      - ./data:/app/data
      - /mnt/unraid/photo/_backup/albums:/photo/albums:ro
      - /mnt/unraid/photo/_backup/inbox:/photo/inbox:ro
      - /mnt/unraid/photo/_backup/timeline:/photo/timeline:ro
      #- /volume1/homes/ExampleUser/Drive/Moments:/exampleuser:ro

  photofield-ai:
    image: ghcr.io/smilyorg/photofield-ai:latest
    container_name: photofield-ai
    ports:
      - 8081:8081
    user: 1000:1000
```

**Expected behavior**
It runs :)

**Additional context**
It is an LXC inside Proxmox, mybe there is different FS acces or whatever. But any other apps runs well the same way
