### ISSUE TITLE
add admin username/password

### ISSUE THREAD

**Issue by prabirshrestha** [SmilyOrg/photofield#28]
You seem to have mentioned in readme that you plan to support it later.

>No user accounts. Not the focus right now. You can define separate collections for separate users based on the directory structure, but there is no authentication or authorization support.

Would it be possible to add basic support for admin only account. Probably in configuration.yml

```yaml
password: "some_hashed_password"
collections:
   .....
   .....
```
